spring:
  application:
    name: order-service
server:
  port: 8080

#SWAGGER
springdoc:
  swagger-ui:
    path: /swagger-ui.html

# PRODUCT SERVICE ROOT
api:
  catalog:
    baseurl: http://product-service

#EUREKA
eureka:
  client:
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#ACTUATOR
management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always




